// Base de dados do Radar Jovem — gerada a partir de oportunidades.json (pesquisa verificada em 2026-07-15)
// fases: f1 = 1º–5º ano EF | f2 = 6º–9º ano EF | em = ensino médio | emc = EM concluído
const DB = [
  {
    id: "epcar",
    nome: "EPCAR — Escola Preparatória de Cadetes do Ar",
    categoria: "militar",
    orgao: "Força Aérea Brasileira",
    resumo: "Ensino médio na FAB em Barbacena-MG, com alojamento, soldo e caminho direto para se tornar oficial aviador na AFA.",
    idade_min: 14, idade_max: 18,
    regra_idade: "Não completar 19 anos até 31/12 do ano da matrícula (ano seguinte à prova)",
    fases: ["f2", "em"],
    escolaridade: "Fundamental concluído ou em conclusão",
    gratuito: true, custo: "Taxa de inscrição R$ 100; o curso é gratuito",
    epoca: "Inscrições em março",
    vagas: "~150/ano",
    link: "https://www.fab.mil.br/ingresso",
    status: "verificado"
  },
  {
    id: "afa",
    nome: "AFA — Academia da Força Aérea",
    categoria: "militar",
    orgao: "Força Aérea Brasileira",
    resumo: "Formação de oficial da Aeronáutica (aviador, intendente ou infante) — carreira militar de nível superior.",
    idade_min: 17, idade_max: 22,
    regra_idade: "Faixa 17–22 do portal da FAB — confirme no edital vigente",
    fases: ["em", "emc"],
    escolaridade: "Ensino médio completo até a matrícula",
    gratuito: true, custo: "Taxa de inscrição R$ 120; o curso é gratuito",
    epoca: "Inscrições ~abril (ano anterior ao ingresso)",
    vagas: "~50/ano",
    link: "https://www.fab.mil.br/ingresso",
    status: "verificado"
  },
  {
    id: "colegio-naval",
    nome: "Colégio Naval",
    categoria: "militar",
    orgao: "Marinha do Brasil",
    resumo: "Ensino médio na Marinha em Angra dos Reis-RJ, com caminho para a Escola Naval e a carreira de oficial.",
    idade_min: 15, idade_max: 17,
    regra_idade: "Faixa etária muda por edital — leia o edital do ano (historicamente ~15 a 17)",
    fases: ["f2", "em"],
    escolaridade: "Fundamental completo",
    gratuito: true, custo: "Taxa R$ 100 (isenção CadÚnico e doadores de medula); curso gratuito",
    epoca: "Edital anual — ver concursos.marinha.mil.br",
    vagas: "~155/ano",
    link: "https://www.inscricao.marinha.mil.br",
    status: "verificado"
  },
  {
    id: "espcex",
    nome: "EsPCEx — Escola Preparatória de Cadetes do Exército",
    categoria: "militar",
    orgao: "Exército Brasileiro",
    resumo: "A porta de entrada para ser oficial de carreira do Exército: 1 ano em Campinas-SP com soldo, depois a AMAN. 440 vagas por ano.",
    idade_min: 17, idade_max: 22,
    regra_idade: "17 a 22 anos completados até 31/12 do ano da MATRÍCULA (Edital 2026/27)",
    fases: ["em", "emc"],
    escolaridade: "Cursando a 3ª série do EM (no ano da inscrição) ou EM concluído; brasileiro nato",
    gratuito: true, custo: "Taxa R$ 100 (isenção CadÚnico, baixa renda e doadores de medula); curso gratuito e remunerado",
    epoca: "Inscrições ~abril a junho (ciclo 2026/27 encerrou em 16/06; próximo ~abril/2027); provas em setembro",
    vagas: "440/ano (400 masc + 40 fem)",
    link: "https://espcex.eb.mil.br/index.php/concurso/",
    status: "verificado"
  },
  {
    id: "eear",
    nome: "EEAR — Sargento da Aeronáutica",
    categoria: "militar",
    orgao: "Força Aérea Brasileira",
    resumo: "Formação de sargento da FAB em Guaratinguetá-SP, com soldo durante o curso e carreira estável em dezenas de especialidades.",
    idade_min: 17, idade_max: 24,
    regra_idade: "Mínimo 17 e não completar 25 anos até 31/12 do ano da matrícula",
    fases: ["em", "emc"],
    escolaridade: "EM concluído (ou certificação ENCCEJA); menor de 18 precisa de autorização",
    gratuito: true, custo: "Taxa R$ 100 (isenção CadÚnico e doadores de medula); curso gratuito e remunerado",
    epoca: "Ciclos ~semestrais (CFS 1/2027 encerrou em 06/03/2026) — acompanhe ingresso.eear.fab.mil.br",
    vagas: "~175/ciclo",
    link: "https://ingresso.eear.fab.mil.br/",
    status: "verificado"
  },
  {
    id: "ita",
    nome: "ITA — Instituto Tecnológico de Aeronáutica",
    categoria: "militar",
    orgao: "Força Aérea Brasileira",
    resumo: "A engenharia mais concorrida do Brasil, gratuita, em São José dos Campos-SP. Um dos vestibulares mais respeitados do país.",
    idade_min: null, idade_max: 24,
    regra_idade: "Não completar 25 anos até 31/12 do ano da matrícula; menor de 18 com autorização",
    fases: ["em", "emc"],
    escolaridade: "Ensino médio completo até a matrícula",
    gratuito: true, custo: "Taxa R$ 195 (com isenção para baixa renda — Lei 12.799); curso gratuito",
    epoca: "Inscrições ~junho-julho (Vestibular 2027 encerrou 12/07/2026; próximo ~meados de 2027)",
    vagas: "~200/ano",
    link: "https://www.vestibular.ita.br/",
    status: "verificado"
  },
  {
    id: "ime-cfg",
    nome: "IME — Instituto Militar de Engenharia (CFG)",
    categoria: "militar",
    orgao: "Exército Brasileiro",
    resumo: "Engenharia de elite gratuita no Rio de Janeiro, para quem está saindo do ensino médio — com opção de carreira militar ou reserva.",
    idade_min: 16, idade_max: 22,
    regra_idade: "16 a 22 anos até 31/12 do ano da matrícula (curso CFG, para concluintes do EM)",
    fases: ["em", "emc"],
    escolaridade: "Ensino médio concluído até a matrícula",
    gratuito: true, custo: "Taxa de inscrição; curso gratuito",
    epoca: "Edital anual — ver ime.eb.mil.br",
    vagas: "Ver edital",
    link: "https://www.ime.eb.mil.br/vestibular-e-concursos/cfg-ensino-medio",
    status: "verificado"
  },
  {
    id: "esa",
    nome: "Sargento do Exército (ESA / EsSLog / CIAVEx)",
    categoria: "militar",
    orgao: "Exército Brasileiro",
    resumo: "Formação de sargento de carreira do Exército — emprego estável com soldo desde o primeiro dia de curso.",
    idade_min: 17, idade_max: 24,
    regra_idade: "17–24 anos (área Geral); 17–26 para Música e Saúde — até 31/12 do ano da matrícula",
    fases: ["em", "emc"],
    escolaridade: "EM completo ou cursando o 3º ano",
    gratuito: true, custo: "Taxa de inscrição; curso gratuito e remunerado",
    epoca: "Edital anual",
    vagas: "~1.100/ano",
    link: "https://www.gov.br/pt-br/servicos/ingressar-na-escola-de-formacao-de-sargentos-de-carreira",
    status: "verificado"
  },
  {
    id: "jovem-senador",
    nome: "Programa Jovem Senador",
    categoria: "cidadania",
    orgao: "Senado Federal",
    resumo: "Concurso de redação: 27 estudantes (1 por estado) passam uma semana em Brasília exercendo mandato simulado de senador — tudo pago.",
    idade_min: null, idade_max: 19,
    regra_idade: "Até 19 anos completos até 31/12 do ano da edição",
    fases: ["em"],
    escolaridade: "Ensino médio de escola pública estadual ou do DF",
    gratuito: true, custo: "Gratuito — viagem e estadia custeadas",
    epoca: "Inscrição ~abril, pela escola",
    vagas: "27/ano",
    link: "https://www12.senado.leg.br/jovemsenador",
    status: "verificado"
  },
  {
    id: "camara-mirim",
    nome: "Câmara Mirim",
    categoria: "cidadania",
    orgao: "Câmara dos Deputados",
    resumo: "Você escreve um projeto de lei e, se selecionado, vota ele de verdade no Plenário da Câmara em Brasília, como deputado mirim.",
    idade_min: null, idade_max: null,
    regra_idade: "5º ao 9º ano do ensino fundamental",
    fases: ["f1", "f2"],
    escolaridade: "5º–9º ano, escola pública ou privada",
    gratuito: true, custo: "Gratuito",
    epoca: "Regulamento ~junho; evento em outubro",
    vagas: "Seleção nacional",
    link: "https://plenarinho.leg.br/index.php/camara-mirim/",
    status: "verificado"
  },
  {
    id: "obmep",
    nome: "OBMEP — Olimpíada de Matemática",
    categoria: "olimpiada",
    orgao: "IMPA / MEC",
    resumo: "A maior olimpíada do país. Medalha abre porta para bolsa de iniciação científica do CNPq e vagas em universidades sem vestibular.",
    idade_min: null, idade_max: null,
    regra_idade: "6º ano do fundamental ao 3º ano do médio",
    fases: ["f2", "em"],
    escolaridade: "6º ano EF ao 3º ano EM",
    gratuito: true, custo: "Gratuito",
    epoca: "Inscrição pela escola ~fev–março",
    vagas: "Aberta a todos",
    link: "https://www.obmep.org.br/",
    status: "conferir"
  },
  {
    id: "pic-obmep",
    nome: "PIC / PICME — bolsa CNPq para medalhistas OBMEP",
    categoria: "olimpiada",
    orgao: "IMPA / CNPq",
    resumo: "Medalhistas da OBMEP recebem bolsa de Iniciação Científica Júnior e aulas com professores universitários.",
    idade_min: null, idade_max: null,
    regra_idade: "Medalhistas da OBMEP (por convite)",
    fases: ["f2", "em"],
    escolaridade: "Premiados na OBMEP",
    gratuito: true, custo: "Gratuito — você RECEBE bolsa",
    epoca: "Convite após o resultado da OBMEP",
    vagas: "Milhares/ano",
    link: "https://www.obmep.org.br/pic.htm",
    status: "conferir"
  },
  {
    id: "vagas-olimpicas",
    nome: "Vagas olímpicas — USP, Unicamp, Unesp, IMPA Tech",
    categoria: "olimpiada",
    orgao: "Universidades públicas",
    resumo: "Mais de 800 vagas de graduação para medalhistas de olimpíadas científicas — sem passar pelo vestibular tradicional.",
    idade_min: null, idade_max: null,
    regra_idade: "Concluintes do EM com medalha em olimpíada reconhecida",
    fases: ["em", "emc"],
    escolaridade: "Ensino médio (medalhista)",
    gratuito: true, custo: "Gratuito",
    epoca: "Editais no 2º semestre",
    vagas: "800+ (2026)",
    link: "https://www.obm.org.br/2025/11/19/universidades-ampliam-vagas-olimpicas-para-2026-e-reforcam-valorizacao-de-medalhistas/",
    status: "conferir"
  },
  {
    id: "uwc",
    nome: "UWC — bolsa para estudar no exterior (18 países)",
    categoria: "intercambio",
    orgao: "Comitê UWC Brasil",
    resumo: "2 anos de ensino médio internacional (IB) em colégios United World Colleges pelo mundo, com bolsas integrais e parciais.",
    idade_min: 15, idade_max: 18,
    regra_idade: "15–18 anos completos até 31/08 do ano de ingresso",
    fases: ["em"],
    escolaridade: "Cursando 1º ou 2º ano do EM",
    gratuito: false, custo: "80% dos selecionados recebem bolsa total ou parcial",
    epoca: "Seleção anual — ver site do comitê",
    vagas: "~dezenas/ano",
    link: "https://www.br.uwc.org/requisitos",
    status: "conferir",
    mundo: true
  },
  {
    id: "jovens-embaixadores",
    nome: "Jovens Embaixadores (EUA)",
    categoria: "intercambio",
    orgao: "Embaixada dos EUA",
    resumo: "Intercâmbio de ~3 semanas nos Estados Unidos, 100% pago, para alunos de escola pública com voluntariado e bom inglês.",
    idade_min: 15, idade_max: 18,
    regra_idade: "Janela de nascimento muda por edição (2027: nascidos 03/2008–01/2011)",
    fases: ["em"],
    escolaridade: "Ensino médio de escola pública",
    gratuito: true, custo: "Totalmente custeado",
    epoca: "Cronograma anual — Partners of the Americas",
    vagas: "Seleção nacional",
    link: "https://partners.org.br/jovens-embaixadores/inscricoes/",
    status: "conferir",
    mundo: true
  },
  {
    id: "etec",
    nome: "ETECs — ensino técnico gratuito (SP)",
    categoria: "educacao",
    orgao: "Centro Paula Souza (SP)",
    resumo: "Ensino médio integrado ao técnico ou curso técnico gratuito nas escolas técnicas estaduais de São Paulo.",
    idade_min: null, idade_max: null,
    regra_idade: "Sem limite de idade — por fase escolar",
    fases: ["f2", "em", "emc"],
    escolaridade: "Fundamental completo (integrado) ou 2ª série EM+ (técnico)",
    gratuito: true, custo: "Curso gratuito; taxa no Vestibulinho",
    epoca: "Vestibulinho semestral",
    vagas: "Dezenas de milhares",
    link: "https://vestibulinho.etec.sp.gov.br/",
    status: "conferir",
    uf: "SP"
  },
  {
    id: "ifs",
    nome: "Institutos Federais — técnico integrado",
    categoria: "educacao",
    orgao: "Rede Federal / MEC",
    resumo: "Ensino médio + curso técnico gratuito e de alta qualidade nos IFs de todo o Brasil.",
    idade_min: null, idade_max: null,
    regra_idade: "Por fase escolar",
    fases: ["f2", "em", "emc"],
    escolaridade: "Fundamental completo (integrado) ou EM completo (subsequente)",
    gratuito: true, custo: "Gratuito",
    epoca: "Editais no 2º semestre (ingresso no ano seguinte)",
    vagas: "Por campus",
    link: "https://www.gov.br/mec/pt-br",
    status: "conferir"
  },
  {
    id: "jovem-aprendiz",
    nome: "Jovem Aprendiz",
    categoria: "trabalho",
    orgao: "Lei da Aprendizagem / CIEE",
    resumo: "Primeiro emprego com carteira assinada + curso de formação, meio período, compatível com a escola.",
    idade_min: 14, idade_max: 24,
    regra_idade: "14–24 anos (sem limite para pessoas com deficiência)",
    fases: ["f2", "em", "emc"],
    escolaridade: "Cursando ou tendo concluído fundamental/médio",
    gratuito: true, custo: "É remunerado — você recebe salário",
    epoca: "Vagas abertas o ano todo",
    vagas: "Contínuas",
    link: "https://portal.ciee.org.br/",
    status: "conferir"
  },
  {
    id: "eua-need-blind",
    nome: "Harvard, MIT, Yale, Princeton e Amherst — bolsa integral",
    categoria: "faculdade",
    orgao: "Universidades dos EUA (need-blind)",
    resumo: "As 5 universidades need-blind dos EUA: sua renda não afeta a admissão. Em Harvard, família com renda abaixo de ~US$ 100 mil não paga NADA — nem moradia, nem comida.",
    idade_min: null, idade_max: null,
    regra_idade: "Sem limite formal — aplicação típica no último ano do EM",
    fases: ["em", "emc"],
    escolaridade: "Ensino médio + TOEFL/SAT + redações e cartas de recomendação",
    gratuito: true, custo: "Bolsa cobre 100% da necessidade financeira, sem empréstimos",
    epoca: "Common App: agosto–janeiro do último ano do EM",
    vagas: "Competitivo, mas real",
    link: "https://college.harvard.edu/financial-aid",
    status: "verificado",
    mundo: true
  },
  {
    id: "education-usa",
    nome: "EducationUSA — orientação gratuita para estudar nos EUA",
    categoria: "faculdade",
    orgao: "Departamento de Estado dos EUA",
    resumo: "Rede oficial com centros no Brasil que orienta de graça todo o processo de aplicação — e o programa Opportunity Funds pode custear taxas e provas para baixa renda.",
    idade_min: null, idade_max: null,
    regra_idade: "Qualquer idade — o ideal é começar 2 anos antes de aplicar",
    fases: ["em", "emc"],
    escolaridade: "Cursando ou tendo concluído o ensino médio",
    gratuito: true, custo: "Orientação gratuita",
    epoca: "Contínua",
    vagas: "Aberto a todos",
    link: "https://educationusa.state.gov/find-advising-center",
    status: "verificado",
    mundo: true
  },
  {
    id: "mext",
    nome: "MEXT — graduação no Japão 100% paga",
    categoria: "faculdade",
    orgao: "Governo do Japão (Embaixada/Consulados)",
    resumo: "Bolsa do governo japonês: passagem, mensalidade e isenção total de taxas para fazer a faculdade inteira no Japão. Prova escrita e entrevista no consulado.",
    idade_min: 17, idade_max: 24,
    regra_idade: "17 a 24 anos, com 12 anos de escolaridade completos",
    fases: ["em", "emc"],
    escolaridade: "EM completo (ou em conclusão) + inglês ou japonês",
    gratuito: true, custo: "Tudo pago + bolsa mensal",
    epoca: "Inscrições ~abril–junho nos consulados",
    vagas: "Anual",
    link: "https://www.br.emb-japan.go.jp/itpr_pt/graduacao.html",
    status: "verificado",
    mundo: true
  },
  {
    id: "enem-portugal",
    nome: "Universidades de Portugal via nota do ENEM",
    categoria: "faculdade",
    orgao: "Universidades portuguesas (Coimbra, Porto, Aveiro…)",
    resumo: "Dezenas de universidades de Portugal aceitam a nota do ENEM no lugar de vestibular — mesma língua, diploma europeu, e mensalidades bem menores que faculdades privadas brasileiras.",
    idade_min: null, idade_max: null,
    regra_idade: "Sem limite de idade",
    fases: ["em", "emc"],
    escolaridade: "EM completo + nota do ENEM",
    gratuito: false, custo: "Pagas (propinas ~€3-7 mil/ano), com bolsas em alguns casos",
    epoca: "Editais anuais por universidade",
    vagas: "Dezenas de instituições",
    link: "https://www.uc.pt/candidatos-internacionais/",
    status: "conferir",
    mundo: true
  },
  {
    id: "erasmus-mundus",
    nome: "Erasmus Mundus — mestrado na Europa com bolsa integral",
    categoria: "faculdade",
    orgao: "União Europeia",
    resumo: "Mestrados em 2+ países europeus com bolsa que cobre curso, viagem e custo de vida. Para quem já terminou (ou está terminando) a graduação.",
    idade_min: null, idade_max: null,
    regra_idade: "Sem limite de idade — exige graduação concluída",
    fases: ["emc"],
    escolaridade: "Graduação completa + inglês",
    gratuito: true, custo: "Bolsa integral + ajuda de custo",
    epoca: "Candidaturas ~out–jan de cada ano",
    vagas: "Centenas de programas",
    link: "https://erasmus-plus.ec.europa.eu/opportunities/opportunities-for-individuals/students/erasmus-mundus-joint-masters-scholarships",
    status: "conferir",
    mundo: true
  },
  {
    id: "rotary-intercambio",
    nome: "Rotary Youth Exchange — intercâmbio de ensino médio",
    categoria: "intercambio",
    orgao: "Rotary International (clubes locais)",
    resumo: "Um ano letivo no exterior morando com famílias anfitriãs, por uma fração do preço de agências — os clubes Rotary cobrem boa parte dos custos.",
    idade_min: 15, idade_max: 18,
    regra_idade: "15 a 18 anos na maioria dos distritos (varia)",
    fases: ["em"],
    escolaridade: "Cursando ensino médio",
    gratuito: false, custo: "Custo reduzido (clube cobre hospedagem e escola)",
    epoca: "Procurar o clube Rotary da sua cidade ~1 ano antes",
    vagas: "Por distrito",
    link: "https://www.rotary.org/pt/our-programs/youth-exchanges",
    status: "conferir",
    mundo: true
  },
  {
    id: "liga-jovem",
    nome: "Desafio Liga Jovem (Sebrae)",
    categoria: "empreendedorismo",
    orgao: "Sebrae",
    resumo: "Competição nacional de empreendedorismo para estudantes criarem soluções e concorrerem a prêmios.",
    idade_min: null, idade_max: null,
    regra_idade: "Fundamental II ao médio/técnico (ver regulamento da edição)",
    fases: ["f2", "em"],
    escolaridade: "Fundamental II ao médio/técnico",
    gratuito: true, custo: "Gratuito, com premiação",
    epoca: "Edição anual",
    vagas: "Equipes de todo o país",
    link: "https://www.desafioligajovem.com.br/",
    status: "conferir"
  }
];

const CATEGORIAS = {
  militar: { label: "Carreira militar", icone: "🎖️" },
  cidadania: { label: "Cidadania e política", icone: "🏛️" },
  olimpiada: { label: "Olimpíadas científicas", icone: "🏅" },
  intercambio: { label: "Intercâmbio", icone: "✈️" },
  faculdade: { label: "Faculdade no exterior", icone: "🌍" },
  educacao: { label: "Ensino técnico", icone: "🎓" },
  trabalho: { label: "Trabalho e renda", icone: "💼" },
  empreendedorismo: { label: "Empreendedorismo", icone: "🚀" }
};

const FASE_ORDER = { f1: 1, f2: 2, em: 3, emc: 4 };
